### ISSUE TITLE
change "website title" in index

### ISSUE THREAD

**Issue by n-bakken** [n-bakken/gdsc-website#27]
this will change the title that shows on the browser tab, its one line of code edit!

**Comment by HowardLee134** [comment]
I will do it rn

**Comment by HowardLee134** [comment]
So after trying several ways still get the same error: 
To https://github.com/n-bakken/gdsc-website-comp195.git
 ! [rejected]        27-change-website-title-in-index -> 27-change-website-title-in-index (non-fast-forward)
error: failed to push some refs to 'https://github.com/n-bakken/gdsc-website-comp195.git'
hint: Updates were rejected because the tip of your current branch is behind

whereas I did force push since nobay gonna work on this branch tho
